### PR TITLE
Upgrade button design and add hover effect

### PR DESCRIPTION
**Pull request by CSSandHTMLonly**
Before:
image
After(on hover):
image

Before:
image
after:
image
before
image

after
image

### CODE REVIEW

**Comment by gbtami** [comment]
Don't mix unrelated changes in on PR please. Split them into separate ones.
Ask tomato about grammar before you suggest changes.
Open an issue about your styling changes with screenshot (before-after) to let us see what it will change.

**Comment by gbtami** [comment]
You have to take care of dark theme as well.

**Comment by CSSandHTMLonly** [comment]
Made it like lichess:
image
image

**Comment by gbtami** [comment]
This is not the sane as on lichess.
Thx for all of your efforts, but I can't merge this.

**Pull request closed without merging**
