### PR TITLE
change default scrollbar style

### PR DESCRIPTION
**Pull request by tiagohermano**
I used lichess as reference. solves #335 
Would you be kind to add the label 'hacktoberfest-accepted' to this PR?

### CODE REVIEW

**Comment by gbtami** [comment]
I think this should be defined 
1. globally for all scrollbars
2. different for dark theme (see the css variable section at the top)

**Comment by tiagohermano** [comment]
Yeah, sure. I'll get it done by the end of the week

**Comment by tiagohermano** [comment]
@gbtami I expanded the styles globally and made use of the css variables. There's one minor issue though, the variable --button-text and --button-text-hover has the same value on the light theme, and therefore there is no hover effect. Do you have any suggestions on how to solve this problem?

**Comment by gbtami** [comment]
I think createing new variables for different stuff (button-text vs scrollbar-thumb) is the only correct way to go.

**Comment by gbtami** [comment]
Do you plan to fix the remaining hover issue?
This PR is Ok without that also, so I can merge it if you have no time to work on this more.

**Comment by tiagohermano** [comment]
Sorry on the delayed response, i'll finish it

**Comment by tiagohermano** [comment]
Fixed it. I picked some colors that made sense in my mind but really I left it for you to choose.

**Comment by gbtami** [comment]
Great, thx!

**Pull request merged**
