### PR TITLE
Add cburnett pieces to Makruk

### PR DESCRIPTION
**Pull request by Rechefiltr-is-Fire**
I even made Silver in Keynote from basic pieces, drawings, but based on part of cburnett bishop.

### CODE REVIEW

**Comment by Fulmene** [comment]
My thoughts
1. I would like to see a full board screenshot to judge how it looks in real gameplay.
2. You should probably add this set to Sittuyin and ASEAN too. Especially ASEAN.

**Comment by Rechefiltr-is-Fire** [comment]
@Fulmene See to understand.

**Comment by Fulmene** [comment]
1. Please don't create a whole new issue for this. Just reply here.
2. The tips of the khon pieces look unusually grey. I think it should be more white.
3. The white lines on the black piece is too large. It should be in similar style with the queen. The bottom line should be removed.

**Comment by Rechefiltr-is-Fire** [comment]
OK!!!

**Comment by gbtami** [comment]
Please don't embed pixel images into .svg when the image itself is simple and can be drawn in [Inkscape. ](https://inkscape.org/)

**Comment by Rechefiltr-is-Fire** [comment]
What should I do?;)

**Comment by gbtami** [comment]
Draw it as vector graphics (.svg) instead of pixel graphics (.png).

**Comment by Rechefiltr-is-Fire** [comment]
I haven’t Inkscape!
So it’s svgs

**Comment by gbtami** [comment]
To understand what I'm talking about read https://xd.adobe.com/ideas/principles/app-design/bitmap-vs-vector-images-difference/ please.

**Comment by gbtami** [comment]
No. If you look into your .svg files in Edit mode https://github.com/Rechefiltr-is-Fire/pychess-variants/edit/patch-7/static/images/pieces/green/bS.svg?pr=%2Fgbtami%2Fpychess-variants%2Fpull%2F989
you will see it is just an embedded (base64 encoded) .pgn inside the .svg file.

Real vector graphics contains xml tags and attributes describing the lines, curves, colors, paths in textual format. Here is an example https://github.com/gbtami/pychess-variants/edit/master/static/images/pieces/merida/bF.svg

**Comment by Rechefiltr-is-Fire** [comment]
Hah bro, that I mean SVGs in pull request and closed issue, not small SVGs in my repository.
They are losing quality, alright.

**Comment by gbtami** [comment]
When you fix Fulmene issues 2. and 3. above and recreate the pieces in vector graphics format (not as embedded pixel images) we can add them for sure. Until then I close this.

**Pull request closed without merging**
