### PR TITLE
Fix zoom slider's blurry scale

### PR DESCRIPTION
**Pull request by Ka-hu**
Except for shogi, like I mentioned it on Discord. This blurry scaling problem exists mostly in Chrome/Chromium (and I guess in other Chromium-based browsers). It seems to me that Firefox scales SVG better (not as blurry).

Side note: in Firefox we can click on the slider and use the mouse wheel to zoom in/out (smoother than dragging the slider thumb). This doesn't work in Chrome/Chromium, but I guess it's a browser feature.

### CODE REVIEW

**Comment by Ka-hu** [comment]
I also adjusted the game table header in the lobby (commit: 3268ad8). Screenshot: https://i.imgur.com/4LJeUEG.png
(I can't send a separate pull request for it).

**Comment by gbtami** [comment]
Thx! Seems table header adjustment rendering is different in Firefox/Chrome, but definitely much more nicer than it was before!

**Comment by gbtami** [comment]
Firefox on Ubuntu 18.04 
http://i.imgur.com/p6Lmwsq.png

**Comment by Ka-hu** [comment]
I have Firefox version 74 currently (FF 75  is the newest in Arch Linux, I will update and look at it)
https://i.imgur.com/RypHmX5.png

By the way, it' simple css padding, it should be okay with other versions, too. :thinking:

**Comment by gbtami** [comment]
http://i.imgur.com/Y7whZBX.png

**Comment by Ka-hu** [comment]
Updated my system 15 minutes ago, no problem here: https://i.imgur.com/yEiJbnK.png
Maybe it caused by the different font type.

**Pull request merged**
