### PR TITLE
Make /games show bot level in case of a bot game

### PR DESCRIPTION
**Pull request by Ralgun**
See #972 

- `/games` now shows titles of players in case they have one.
- `/games` now shows bot level of players in case they are a bot.

### CODE REVIEW

**Comment by gbtami** [comment]
Can you test it with slim boards like dobutsu, minishogi, gorogoro please?

I'm afraid without additional layout/css modifications this will break.

**Comment by Ralgun** [comment]
That's annoying. I will see what I can do...
And apologies for the reopen, it seems like I have fat fingers

**Comment by Ralgun** [comment]
I tried making fonts smaller where needed. It works, but I believe it doesn't look as good as it could. I can't really make it better without large rework of `/games` so feel free to close.
image

**Comment by gbtami** [comment]
I think the base of PR is useful and OK, so I merge it.
We can remove the css hack when left side variant menu tabs will be added.
Thx!

**Pull request merged**
