### PR TITLE
Redesigned Blank Shogi Piece, BnW Blank Piece and Invisible Icons

### PR DESCRIPTION
**Pull request by Eventlesstew**
I redesigned the Blank Shogi piece to be more consistent with the blank piece in other variants' sets and also added Black and White Blank Sets too.

I also added an icon for the Invisible pieces in the options menu, Shogi has a special one for consistency.

### CODE REVIEW

**Comment by CricketForJapan** [comment]
I just tried out.  https://www.pychess.org/6f3ulSWG Black moves first in Shogi.  White only move first in handicap games.  I have not tested handicap games, but for standard games it is the wrong way around I believe.  Please can you review this?

**Comment by gbtami** [comment]
Just in case I copy-paste my Discord answer here.
"Thx for the PR. The truth is I can use the "question mark inside the circle" only
because hidden pieces preview icon is variant independent
also the blank pieces for Shogi are good rn and I don't plan to add several "blank" piece sets for any variant."

**Comment by gbtami** [comment]
invisible.svg added.
Thx!

**Comment by Eventlesstew** [comment]
no problem

**Pull request closed without merging**
