### PR TITLE
shogi piece set

### PR DESCRIPTION
**Pull request by Mansindam**

### CODE REVIEW

**Comment by PraseodymiumSpike** [comment]
a little odd some pieces have gradient and some dont

**Comment by gbtami** [comment]
9x9mansindam.svg is not usable for Shogi, because it is exact square shaped. Shogi board dimensions are little bit different. We have 3 checkered Shogi boards already. If you want to create a new one you can use them as starting point.

If you add a new piece set it have to be added to PIECE_FAMILIES at https://github.com/gbtami/pychess-variants/blob/master/client/variants.ts#L52 and also to static/preview.css (before https://github.com/gbtami/pychess-variants/blob/master/static/preview.css#L230) to let it selectable in board settings.

After thinking about it more, I started to like your idea to create a chess like set without those Shogi pentagonal frames, and face to face orientation. But the figures must have a little bit more uniform appearance in general. I mean they are too eclectic atm.
I suggest everyone to read https://www.pychess.org/blogs/Internationalized_Pieces

**Comment by gbtami** [comment]
Some other notes.
Piece sizes should be adjusted a bit to better suite to Shogi board squares.
Some figures have a thick outline, some thin. Possible because you borrowed them from different sets. This should be fixed as well.
This is how it looks now compared to Shogi and Mansindam.

**Comment by gbtami** [comment]
read https://discord.com/channels/634298688663191582/653203449927827456/1287728038326435841

**Pull request closed without merging**
