### PR TITLE
Better instructions about developing

### PR DESCRIPTION
**Pull request by lidevelopers**

### CODE REVIEW

**Comment by Diwaditya** [comment]
Nice. Wait for @gbtami to view! 😄

**Comment by lidevelopers** [comment]
also please check my wiki https://github.com/lidevelopers/pychess-variants/wiki

**Comment by gbtami** [comment]
I think CONTRIBUTING.md is useless in a github repo. Someone who comes to github to contribute should know the basics.
Moving installation instruction from README.md to wiki, and extending it make more sense.

**Comment by Diwaditya** [comment]
@gbtami 
Don't you think we need something like this: _https://lichess.org/help/contribute_ ?

**Comment by gbtami** [comment]
Yes, adding more links to FAQ in  "Can I contribute?" is definitely a good idea.

**Pull request closed without merging**
