### PR TITLE
Better Docs

### PR DESCRIPTION
**Pull request by lidevelopers**

### CODE REVIEW

**Comment by Diwaditya** [comment]
I don't know who can teach you the meaning of "filed" ...

**Comment by TheYoBots** [comment]
Why are commits that have already been pushed onto pychess’ source code being committed again?

**Comment by Diwaditya** [comment]
@TheYoBots maybe LiDeveloper thinks that his previous PR wasn't merged x)

**Comment by lidevelopers** [comment]
I committed 3 or 4 commits but github taken that I was commited only 1 commit

**Comment by gbtami** [comment]
This PR is the same as already merged https://github.com/gbtami/pychess-variants/pull/539

**Comment by Diwaditya** [comment]
@gbtami also merge tournaments PR please!!

**Pull request closed without merging**
