### PR TITLE
Refactor new game ui

### PR DESCRIPTION
**Pull request by randompearl-stack**
- [x] increase heading size
- [x] shorten FEN input
- [x] make slider endpoints accurate 
- [x] decrease “X” size
- [x] increase “X” opacity
- [x] more padding for selectors and sliders
- [x] make casual/rated buttons bigger
- [x] separate color choice buttons more

***
- [ ] click anywhere out to exit

### CODE REVIEW

**Comment by randompearl-stack** [comment]
Firefox Dark and Light Mode

firefoxdark
firefoxlight

Safari Dark and Light Mode

safaridark
safarilight

**Comment by randompearl-stack** [comment]
@gbtami Do you want to implement the last thing which allows users to exit the modal by clicking outside the container?

**Comment by gbtami** [comment]
Btw the "Spectators:..." below the game chat was left aligned before.
Not it is centered. Maybe this regression was caused one of your PRs. I'm not sure though.
Maybe you can remember something :)

**Comment by randompearl-stack** [comment]
Yeah, it is caused by [#1355](https://github.com/gbtami/pychess-variants/pull/1355/files#diff-ad062471b4ed57504bc436e5b3a28c560201b77ec2f4e5ec4133918c09aa542cR450). Also this is the second regression, the first was when I gave padding to the import game button on the profile in #1358. I don't even know how no one noticed that for like two days (at least I didn't).

**Pull request merged**
