### PR TITLE
Zen Mode

### LINKED ISSUE #555: [Feature request] Zen mode
The idea would be to have the same as lichess, a customizable setting to enable/disable Zen Mode, in which some things (chat, player names and ratings on the left, opponent's rating on the right, move list and bottom crosstable) would be hidden so the player can focus only on the game (board and clocks).

For some players is really useful, especially in team competitions like the zh960 league, as seeing things like the spectators is bad for nerves.

### PR DESCRIPTION
**Pull request by pepellou**
Fixes #555 
--

Adds a setting for Zen Mode (On/Off) defaulted to Off.

Inspired by lichess, Zen Mode hides:
 * Player names and ratings
 * Left sidebar (chat, game info)
 * Main top menu
 * Spectators

It also adds a top left button 'ZEN MODE' to go back to normal.

### CODE REVIEW

**Comment by Diwaditya** [comment]
@pepellou 
You are doing great! Go Pepe !

**Comment by pepellou** [comment]
A couple of questions about the failing checks @gbtami 

`DeepSource: Javascript` mentions I introduced 3 antipatterns, but they're following the convention of the code around. Should I not worry about these? 😬 

`Python-CI / build` if I'm not mistaken the server unit tests failed? How's that possible if I only added client diff? 🤔

**Comment by gbtami** [comment]
Thx a lot!

No need to worry about deepsource. It find countless antipatterns we may or may not want to "fix". All are harmless.
Python3.9 test failed in RR tournament test. Interestingly it was OK with Python3.8
Seems it is not deterministic. I will fix it later anyhow.

**Comment by gbtami** [comment]
Btw I find one minor issue. If I make zen mode ON, start a game, then click on the top left button switch to make it OFF,
it is all OK, except if I go to settings again, it shows it as ON.

**Comment by Diwaditya** [comment]
@gbtami 
Whatever, it shouldn't do any harm in the mobile site! :D
Seriously, I can't believe myself how can be a super feature like **zen mode** arrive within a day!

**Comment by pepellou** [comment]
I see. I'll have a look later, thanks!

**Pull request merged**
