### PR TITLE
Better Docs

### PR DESCRIPTION
**Pull request by lidevelopers**

### CODE REVIEW

**Comment by gbtami** [comment]
I think this sentence
"Ultimately it needs to be filed in Github issue tracker"
shouldn't be chneged to
"Ultimately it needs to be filled in Github issue tracker"

**Comment by Diwaditya** [comment]
@lidevelopers 
Well done! But the sentence ""Ultimately it needs to be **filed** in Github issue tracker" isn't typo.
The word **filed** has its own meaning: 

file1
/fʌɪl/
Learn to pronounce
verb
past tense: filed; past participle: filed
place (a document) in a cabinet, box, or folder in a particular order.

_from Google_

**Comment by lidevelopers** [comment]
@gbtami now can you check it?

**Comment by lidevelopers** [comment]
@gbtami Are you merging

**Comment by gbtami** [comment]
Thx!

**Pull request merged**
