### PR TITLE
Update analysisCtrl.ts

### PR DESCRIPTION
**Pull request by helloplaychess**
added spacing to analysis for better visibility

### CODE REVIEW

**Comment by gbtami** [comment]
Maybe I'm blind, but I can't see any difference. May I ask you to create a github issue  with before/after screenshots please?

**Comment by helloplaychess** [comment]
right now: https://prnt.sc/26hje8r and https://prnt.sc/26hje1v
in the screenshot with one dot you can see space between the dot and the move, with the three dots there is no space

there are also a few errors associated with the "moveIndex" can you tell me where the moveIndex is being used?

pychess-variants.js.br?v=4e55b1087aa2819d56013e5c2a59ece9c2865bec:2 The given uciMove '13...hxg4' for position '2r1kb1r/pp1b1pp1/2n1p3/3pP2p/1P1P2Pq/P6P/1B3P2/RN1QKBR1 b Qk - 1 13' is invalid.

this for example, tries to use the moveIndex to add the three dots where they are unnecessary and causing this error-message.

**Comment by gbtami** [comment]
I think you find some dead code we should remove :) Nice catch!
Try to look in https://github.com/gbtami/pychess-variants/blob/master/client/movelist.ts#L72 instead.

**Comment by gbtami** [comment]
Removed it.

**Pull request closed without merging**
