### PR TITLE
Cburnett (Thai elephants)

### PR DESCRIPTION
**Pull request by Rechefiltr-is-Fire**
`attempt 2)`

### CODE REVIEW

**Comment by gbtami** [comment]
Thx!

**Comment by Rechefiltr-is-Fire** [comment]
Thx too;)!

**Comment by gbtami** [comment]
Btw it would be nice to have different image for promoted pawns as well  (similar to merida).

**Comment by gbtami** [comment]
@Rechefiltr-is-Fire this guy (on the right side)

**Comment by Rechefiltr-is-Fire** [comment]
https://github.com/gbtami/pychess-variants/pull/1075

**Pull request merged**
