### PR TITLE
Orda Lancers; Asean, Sittuyin and Spartan pieces

### PR DESCRIPTION
**Pull request by Rechefiltr-is-Fire**

### CODE REVIEW

**Comment by gbtami** [comment]
@CouchTomato87 can you review this PR please?

**Comment by Rechefiltr-is-Fire** [comment]
Sorry that cburnett pieces aren't in asean and sittuyin

**Comment by gbtami** [comment]
Hmm. What Asean and Sittuyin has to do with lancer ribbons?

**Comment by Rechefiltr-is-Fire** [comment]
Sorry but it's my contributions to Pychess also rejected there

**Comment by Rechefiltr-is-Fire** [comment]
I made stronger lancers ribbons because they were outstyle. I also made cburnett ASEAN and Sittuyin CSS files. 

I want to make Spartan Merida alternative set (as alternative Capablanca and Seirawan sets) and probably new variant and new set to Dobutsu. It was my mistake to not give a description in first comment

**Comment by Rechefiltr-is-Fire** [comment]
Standing water or running river?....

**Comment by gbtami** [comment]
@CouchTomato87 ?

**Comment by gbtami** [comment]
Split off different variant stuff to different PRs please, to let us decide on them individually. Thx.

**Comment by Rechefiltr-is-Fire** [comment]
All my commits go to this PR automatically

**Comment by gbtami** [comment]
Create and use different git branches for different pull requests (not the master branch!).

**Comment by Rechefiltr-is-Fire** [comment]
I will not remake this.

**Comment by gbtami** [comment]
I suggest to continue this discussion about your pieces on pychess Discord on https://discord.gg/aPs8RKr
and when there is a consensus we can go back here to finalize the changes. There you can present some screenshots and svg to Ada, CouchTomato and others, to let them comment on it.

**Comment by gbtami** [comment]
Btw ASEAN and Sittuyin cburnett piece sets was already added to pychess before.

**Pull request closed without merging**
